apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/version: 8.1.3
    helm.sh/chart: valkey-3.0.22
  name: netbox-demo-valkey-primary
  namespace: netbox-demo
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp-redis
    nodePort: null
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/name: valkey
  sessionAffinity: None
  type: ClusterIP
