apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: EvictPodsForLowNodeUtilization
        pluginConfig:
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "pods": 20
            targetThresholds:
              "pods": 30
            metricsUtilization:
              metricsServer: true
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"

# - name: EvictLongRunningPods
#   pluginConfig:
#   - name: "PodLifeTime"
#     args:
#       maxPodLifeTimeSeconds: 1209600  # 14 days
#       states:
#       - "Running"
#   plugins:
#     deschedule:
#       enabled:
#         - "PodLifeTime"