apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
metadata:
  name: EvictPodsForLowNodeUtilization
profiles:
  - name: EvictPodsForLowNodeUtilization
    pluginConfig:
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "pods": 20
        targetThresholds:
          "pods": 30
        metricsUtilization:
          metricsServer: true
    plugins:
      balance:
        enabled:
          - "LowNodeUtilization"