apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
metadata:
  name: EvictLongRunningPods
profiles:
  - name: EvictLongRunningPods
    pluginConfig:
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 1209600  # 14 days
        states:
        - "Running"
    plugins:
      deschedule:
        enabled:
          - "PodLifeTime"