apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-hosts-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.8.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k8s-host-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - k8s-hosts-address-pool