apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.3.4
    helm.sh/chart: netbox-6.0.59
  name: netbox-demo-test-connection
  namespace: netbox-demo
spec:
  containers:
  - args:
    - netbox-demo:80
    command:
    - wget
    image: busybox:1.37.0
    imagePullPolicy: IfNotPresent
    name: wget
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 2Gi
        memory: 192Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi
  restartPolicy: Never
