---
- name: Configure cluster DNS
  hosts: ocp-lab-dns.rh-lab.morey.tech
  gather_facts: false  # Play have very little to do with this host.
  become: true

  tasks:
    - name: Add DNS zone to named.conf.options  # noqa: run-once[task]
      ansible.builtin.blockinfile:
        path: /etc/bind/named.conf.options
        block: |
          zone "{{ cluster_name }}.{{ cluster_dns_zone }}" {
              type master;
              file "/etc/bind/db.{{ cluster_name }}.{{ cluster_dns_zone }}";
          };
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        insertafter: "EOF"
        append_newline: true
        prepend_newline: true
        state: present
      notify: Restart BIND9
      become: true

    - name: Configure DNS zone  # noqa: run-once[task]
      ansible.builtin.template:
        src: db.j2
        dest: "/etc/bind/db.{{ cluster_name }}.{{ cluster_dns_zone }}"
        mode: '0644'
      notify: Restart BIND9
      vars:
        dns_records:
          - { name: "api", ip: "{{ api_vips.0.ip }}" }
          - { name: "api-int", ip: "{{ api_vips.0.ip }}" }
          - { name: "*.apps", ip: "{{ ingress_vips.0.ip }}" }

  handlers:
    - name: Restart BIND9
      ansible.builtin.service:
        name: bind9
        state: reloaded

- name: Set Up ocp-lab node VMs
  hosts: ocp-lab-nodes
  gather_facts: false  # Hosts aren't available, since this playbook creates them.

  vars:
    create_assisted_installer: false

  tasks:
    - name: Create Assisted Installer Cluster  # noqa: run-once[task]
      rhpds.assisted_installer.create_cluster:
        name: "{{ cluster_name }}"
        openshift_version: "{{ cluster_version }}"
        base_dns_domain: "{{ cluster_dns_zone }}"
        offline_token: "{{ offline_token }}"
        pull_secret: "{{ pull_secret | to_json }}"
        high_availability_mode: "{{ high_availability_mode }}"
        cluster_network_cidr: "{{ cluster_network_cidr }}"
        cluster_network_host_prefix: "{{ cluster_network_host_prefix }}"
        service_networks: "{{ service_networks }}"
        machine_networks: "{{ machine_networks }}"
        api_vips: "{{ api_vips }}"
        ingress_vips: "{{ ingress_vips }}"
        ssh_public_key: "{{ ssh_authorized_keys }}"
      delegate_to: localhost
      run_once: true
      register: newcluster
      when: create_assisted_installer

    - name: Print link to assisted installer # noqa: run-once[task]
      ansible.builtin.debug:
        msg: "https://console.redhat.com/openshift/assisted-installer/clusters/{{ newcluster.result.id }}"
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer

    # Download discovery.iso to storage-pve.
    - name: Create Discovery ISO # noqa: run-once[task]
      rhpds.assisted_installer.create_infra_env:
        name: "{{ cluster_name }}-infra-env"
        image_type: "{{ image_type }}"
        cluster_id: "{{ newcluster.result.id }}"
        ssh_authorized_key: "{{ ssh_authorized_keys }}"
        offline_token: "{{ offline_token }}"
        pull_secret: "{{ pull_secret | to_json }}"
        openshift_version: "{{ cluster_version }}"
      register: newinfraenv
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer

    - name: Download Discovery ISO  # noqa: run-once[task]
      ansible.builtin.get_url:
        url: "{{ newinfraenv.result.download_url }}"
        dest: "/mnt/pve/storage-pve/template/iso/{{ cluster_name }}-{{ newcluster.result.id }}-discovery.iso"
        mode: '0777'
        force: true
      delegate_to: "{{ groups['pvems'][0] }}"  # Pick a host from the hypervisor group
      run_once: true
      when: create_assisted_installer
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html#run-tasks-concurrently-poll-0

    - name: Create DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        netif: opt3  # rh_lab
        hostname: "{{ inventory_hostname_short }}"
        macaddr: "{{ mac_address }}"
        ipaddr: "{{ ip_address }}"
        ddnsdomainkeyalgorithm: "hmac-md5"  # fixes diff.
        state: present
      delegate_to: pfsense.home.morey.tech
      throttle: 1

    - name: Create new PVE pool  # noqa: run-once[task]
      community.general.proxmox_pool:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        poolid: "{{ cluster_name }}"
        comment: "{{ cluster_name }} cluster"
      delegate_to: localhost
      run_once: true

    - name: Create VMs
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        vmid: "{{ pve_vm_id }}"
        name: "{{ inventory_hostname_short }}"
        node: "{{ pve_node }}"
        pool: "{{ cluster_name }}"
        cpu: x86-64-v2-AES
        cores: 8
        memory: 16384
        ide:
          ide2: "storage-pve:iso/{{ cluster_name }}-{{ newcluster.result.id }}-discovery.iso,media=cdrom"
        scsihw: virtio-scsi-single
        scsi:
          scsi0: 'local-nvme:128,iothread=1'
        net:
          net0: 'virtio={{ mac_address }},bridge=vmbr0,tag=6,firewall=1'
      delegate_to: localhost

    - name: Pause before starting VMs
      ansible.builtin.wait_for:
        timeout: 3
      delegate_to: localhost

    - name: Start VMs
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        vmid: "{{ pve_vm_id }}"
        name: "{{ inventory_hostname_short }}"
        node: "{{ pve_node }}"
        state: started
      delegate_to: localhost

    - name: Wait for the hosts to be ready  # noqa: run-once[task]
      rhpds.assisted_installer.wait_for_hosts:
        cluster_id: "{{ newcluster.result.id }}"
        offline_token: "{{ offline_token }}"
        expected_hosts: "{{ play_hosts | length }}"
        wait_timeout: 300  # Usually ready in 3 - 4 minutes with "full" discovery ISO.
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer

    - name: Start cluster installation  # noqa: run-once[task]
      rhpds.assisted_installer.install_cluster:
        cluster_id: "{{ newcluster.result.id }}"
        offline_token: "{{ offline_token }}"
        wait_timeout: 1200
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer

    - name: Obtain OpenShift cluster credentials  # noqa: run-once[task]
      register: credentials
      rhpds.assisted_installer.get_credentials:
        cluster_id: "{{ newcluster.result.id }}"
        offline_token: "{{ offline_token }}"
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer

    - name: Display credentials  # noqa: run-once[task]
      ansible.builtin.debug:
        var: credentials.result
      delegate_to: localhost
      run_once: true
      when: create_assisted_installer
