---
- name: Set Up ocp-lab node VMs
  hosts: ocp-lab
  gather_facts: false  # Hosts aren't available, since this playbook creates them.

  vars:
    authorized_keys_path: '/root/.ssh/authorized_keys'
    cluster_name: ocp-lab
    cluster_version: 4.18.5
    base_dns_domain: "{{ cluster_name }}.rh-lab.morey.tech"
    image_name: '{{ cluster_name }}-discovery.iso'

  tasks:
    # Create cluster in console.redhat.com assisted installer.
    # https://console.redhat.com/openshift/assisted-installer/clusters
    # - Select "User-Managed Networking".

    # Download discovery.iso to storage-pve.

    - name: Create VMs
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        vmid: "{{ pve_vm_id }}"
        name: "{{ inventory_hostname_short }}"
        node: "{{ pve_node }}"
        cpu: x86-64-v2-AES
        cores: 8
        memory: 16384
        ide:
          ide2: "storage-pve:iso/{{ image_name }},media=cdrom"
        scsihw: virtio-scsi-single
        scsi:
          scsi0: 'local-nvme:128,iothread=1'
        net:
          net0: 'virtio={{ mac_address }},bridge=vmbr0,tag=6,firewall=1'
      delegate_to: localhost

    # Create statis DHCP entries in pfSense.

    # Update load balancer with IPs of nodes?

    # Create DNS entires for:
    # - ocp-lab-01.rh-lab.morey.tech
    # * apps.ocp-lab-01.rh-lab.morey.tech
