---
- name: Destroy ocp-lab node VMs
  hosts: ocp-lab
  gather_facts: false  # Hosts may not be available, since this playbook destroys them.

  vars:
    cluster_name: 'ocp-lab'

  vars_prompt:
    - name: "destory_confirmation"
      prompt: "Do you want to destory the vms? (yes/no)?"
      private: false

  tasks:
    - name: Fail if not "yes"
      ansible.builtin.fail:
      when: "destory_confirmation != 'yes'"

    - name: Check if VM exists
      community.general.proxmox_vm_info:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        vmid: "{{ pve_vm_id }}"
        name: "{{ inventory_hostname_short }}"
        node: "{{ pve_node }}"
        config: current
      delegate_to: localhost
      register: vm_state

    - name: Destroy VMs
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        vmid: "{{ pve_vm_id }}"
        name: "{{ inventory_hostname_short }}"
        node: "{{ pve_node }}"
        state: absent
        force: true
      delegate_to: localhost
      when: "vm_state.proxmox_vms != []"
