apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg-ai
  resources:
    requests:
      storage: 50Gi
