apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anythingllm-ynab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: anythingllm-ynab
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: YNAB_API_TOKEN
      remoteRef:
        key: 1aa42e55-bbd7-4af8-9c28-b4dd00dc69cd
        property: password
