apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-system
# resources:
#   - 

helmCharts:
- name: kube-prometheus-stack
  includeCRDs: true
  version: 45.6.0
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: prometheus-system
  # valuesInline:
