apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rr-lessons-discord
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: rr-lessons-discord
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: webhook-url
      remoteRef:
        key: 80644688-fc2a-483a-b1d5-b4df000e7b11
        property: password
