apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - secret.yaml

patches:
- path: deployment-patch.yaml

helmCharts:
- name: home-assistant
  includeCRDs: true
  version: 8.8.3
  repo: https://k8s-at-home.com/charts/
  releaseName: home-assistant
  namespace: home-assistant
  valuesInline:
    image:
      tag: 2.12.1
      pullPolicy: IfNotPresent
    env:
      home-assistant_TIME_ZONE: America/New_York
      home-assistant_OCR_LANGUAGE: eng
      home-assistant_CONSUMER_POLLING: 60
      home-assistant_REDIS: redis://home-assistant-redis-headless:6379
      home-assistant_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'  # https://github.com/home-assistant-ngx/home-assistant-ngx/discussions/4047#discussion-5544405
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: ingress-nginx-internal
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          # nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          # # Set the target to the cluster apex domain.
          # # Defaults to the LoadBalancer IP, which is local only.
          # external-dns.alpha.kubernetes.io/target: rubrik.lab.home.morey.tech
          # # Enable External DNS for this Ingress.
          # external-dns.alpha.kubernetes.io/exclude: 'true'
        hosts:
          - host: home-assistant.rubrik.lab.home.morey.tech
            paths:
            - path: /
              pathType: Prefix
        tls:
        - secretName: home-assistant.rubrik.lab.home.morey.tech
          hosts:
          - home-assistant.rubrik.lab.home.morey.tech
    persistence:
      consume:
        enabled: true
        type: nfs
        server: "192.168.3.19"
        path: /storage-mass/rubrik/home-assistant/consume
        mountPath: /usr/src/home-assistant/consume
      data:
        enabled: true
        # nameOverride: home-assistant-data
        storageClass: longhorn
        size: 25Gi
      media:
        enabled: true
        # nameOverride: home-assistant-media
        storageClass: longhorn
        size: 25Gi
        mountPath: /usr/src/home-assistant/media
      export:
        enabled: true
        # nameOverride: home-assistant-export
        storageClass: longhorn
        size: 25Gi
        mountPath: /usr/src/home-assistant/export
    redis:
      enabled: true
      image:
        pullPolicy: IfNotPresent
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false