apiVersion: v1
data:
  ping_liveness_local.sh: "#!/bin/bash\n\n[[ -f $VALKEY_PASSWORD_FILE ]] && export\
    \ VALKEY_PASSWORD=\"$(< \"${VALKEY_PASSWORD_FILE}\")\"\n[[ -n \"$VALKEY_PASSWORD\"\
    \ ]] && export REDISCLI_AUTH=\"$VALKEY_PASSWORD\"\nresponse=$(\n  timeout -s 15\
    \ $1 \\\n  valkey-cli \\\n    -h localhost \\\n    -p $VALKEY_PORT \\\n    ping\n\
    )\nif [ \"$?\" -eq \"124\" ]; then\n  echo \"Timed out\"\n  exit 1\nfi\nresponseFirstWord=$(echo\
    \ $response | head -n1 | awk '{print $1;}')\nif [ \"$response\" != \"PONG\" ]\
    \ && [ \"$responseFirstWord\" != \"LOADING\" ] && [ \"$responseFirstWord\" !=\
    \ \"MASTERDOWN\" ]; then\n  echo \"$response\"\n  exit 1\nfi"
  ping_liveness_local_and_primary.sh: 'script_dir="$(dirname "$0")"

    exit_status=0

    "$script_dir/ping_liveness_local.sh" $1 || exit_status=$?

    "$script_dir/ping_liveness_primary.sh" $1 || exit_status=$?

    exit $exit_status'
  ping_liveness_primary.sh: "#!/bin/bash\n\n[[ -f $VALKEY_PRIMARY_PASSWORD_FILE ]]\
    \ && export VALKEY_PRIMARY_PASSWORD=\"$(< \"${VALKEY_PRIMARY_PASSWORD_FILE}\"\
    )\"\n[[ -n \"$VALKEY_PRIMARY_PASSWORD\" ]] && export REDISCLI_AUTH=\"$VALKEY_PRIMARY_PASSWORD\"\
    \nresponse=$(\n  timeout -s 15 $1 \\\n  valkey-cli \\\n    -h $VALKEY_PRIMARY_HOST\
    \ \\\n    -p $VALKEY_PRIMARY_PORT_NUMBER \\\n    ping\n)\nif [ \"$?\" -eq \"124\"\
    \ ]; then\n  echo \"Timed out\"\n  exit 1\nfi\nresponseFirstWord=$(echo $response\
    \ | head -n1 | awk '{print $1;}')\nif [ \"$response\" != \"PONG\" ] && [ \"$responseFirstWord\"\
    \ != \"LOADING\" ]; then\n  echo \"$response\"\n  exit 1\nfi"
  ping_readiness_local.sh: "#!/bin/bash\n\n[[ -f $VALKEY_PASSWORD_FILE ]] && export\
    \ VALKEY_PASSWORD=\"$(< \"${VALKEY_PASSWORD_FILE}\")\"\n[[ -n \"$VALKEY_PASSWORD\"\
    \ ]] && export REDISCLI_AUTH=\"$VALKEY_PASSWORD\"\nresponse=$(\n  timeout -s 15\
    \ $1 \\\n  valkey-cli \\\n    -h localhost \\\n    -p $VALKEY_PORT \\\n    ping\n\
    )\nif [ \"$?\" -eq \"124\" ]; then\n  echo \"Timed out\"\n  exit 1\nfi\nif [ \"\
    $response\" != \"PONG\" ]; then\n  echo \"$response\"\n  exit 1\nfi"
  ping_readiness_local_and_primary.sh: 'script_dir="$(dirname "$0")"

    exit_status=0

    "$script_dir/ping_readiness_local.sh" $1 || exit_status=$?

    "$script_dir/ping_readiness_primary.sh" $1 || exit_status=$?

    exit $exit_status'
  ping_readiness_primary.sh: "#!/bin/bash\n\n[[ -f $VALKEY_PRIMARY_PASSWORD_FILE ]]\
    \ && export VALKEY_PRIMARY_PASSWORD=\"$(< \"${VALKEY_PRIMARY_PASSWORD_FILE}\"\
    )\"\n[[ -n \"$VALKEY_PRIMARY_PASSWORD\" ]] && export REDISCLI_AUTH=\"$VALKEY_PRIMARY_PASSWORD\"\
    \nresponse=$(\n  timeout -s 15 $1 \\\n  valkey-cli \\\n    -h $VALKEY_PRIMARY_HOST\
    \ \\\n    -p $VALKEY_PRIMARY_PORT_NUMBER \\\n    ping\n)\nif [ \"$?\" -eq \"124\"\
    \ ]; then\n  echo \"Timed out\"\n  exit 1\nfi\nif [ \"$response\" != \"PONG\"\
    \ ]; then\n  echo \"$response\"\n  exit 1\nfi"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: 8.1.3
    helm.sh/chart: valkey-3.0.22
  name: netbox-demo-valkey-health
  namespace: netbox-demo
