apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-home-kubeconfig
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
    controller.devfile.io/mount-to-devworkspace: 'true'
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /etc/ocp-home
    controller.devfile.io/mount-on-start: 'true'
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: ocp-home-tailnet
        cluster:
          server: https://ocp-home-api.tailscale-system.svc.cluster.local
          tls-server-name: ocp-home-api.taile3c3a8.ts.net
    users:
      - name: devspaces-tailnet
        user: {}
    contexts:
      - name: ocp-home-tailnet
        context:
          cluster: ocp-home-tailnet
          user: devspaces-tailnet
    current-context: ocp-home-tailnet
