apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-system
resources:
  - operator-oauth.yaml
  - tailnet-readers.yaml

helmCharts:
  - name: tailscale-operator
    includeCRDs: true
    version: 1.102.4
    repo: https://pkgs.tailscale.com/helmcharts
    releaseName: tailscale-operator
    namespace: tailscale-system
    valuesInline:
      apiServerProxyConfig:
        mode: "true"
      operatorConfig:
        hostname: ocp-home-api
        defaultTags:
          - tag:ocp-home-api
        podSecurityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      proxyConfig:
        defaultTags: tag:ocp-home-proxy
