apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  application.resourceTrackingMethod: annotation
  exec.enabled: "true"
  # Trigger refresh of AppSet.
  resource.customizations.actions.argoproj.io_ApplicationSet: |
    discovery.lua: |
      actions = {}
      actions["refresh"] = {}
      return actions
    definitions:
      - name: refresh
        action.lua: |
          local os = require("os")
          if obj.metadata.annotations == nil then
              obj.metadata.annotations = {}
          end
          obj.metadata.annotations["argoproj.io/refreshedAt"] = os.date("!%Y-%m-%dT%XZ")
          return obj
  # resource.customizations.actions.apps_Deployment: |
  #   discovery.lua: |
  #     actions = {}
  #     actions["Scale to Zero"] = {}
  #     return actions
  #   definitions:
  #     - name: Scale to Zero
  #       action.lua: |
  #         obj.spec.replicas = 0
  #         return obj