apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.3.4
    helm.sh/chart: netbox-6.0.59
  name: netbox-demo
  namespace: netbox-demo
spec:
  ports:
  - name: http
    nodePort: null
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: netbox
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/name: netbox
  sessionAffinity: None
  type: ClusterIP
