apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ombi-proxy
spec:
  ingressClassName: ingress-nginx-internal
  # tls:
  # - hosts:
  #   - ombi.rubrik.lab.home.morey.tech
  #   secretName: tls-dev-com
  rules:
  - host: ombi.rubrik.lab.home.morey.tech
    http:
      paths:
      - backend:
          service:
            name: ombi-proxy
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
  name: ombi-proxy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ombi-proxy
subsets:
- addresses:
  - ip: 192.168.3.124
  ports:
  - port: 5000
