apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: hf-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: 9ca241df-26a6-4ef1-8026-b4d9016ebc27
        property: password
