apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference-server
resources:
  - hf-token-external-secret.yaml
  - models-pvc.yaml
  - download-model-job.yaml
  - serving-runtime.yaml
  - inference-service.yaml
  - client-rbac.yaml
  - anythingllm-rbac.yaml
  - networkpolicy.yaml
