apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-hosts-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.8.0/24
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
spec:
  ipAddressPools:
  - k8s-hosts-address-pool
  aggregationLength: 32 # advertise each route as a /32
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: pfsense-peer
spec:
  myASN: 64501
  peerASN: 64500
  peerAddress: 192.168.3.1