apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-daily-snapshot
  namespace: longhorn-system
spec:
  cron: "* * * * *"
  task: "longhorn-volv-snapshot"
  groups:
  # Having default in groups will automatically schedule this recurring job to any volume with no recurring job.
  - default
  retain: 1
  concurrency: 2
  # labels: