resources:
  - namespace.yaml
  - ingress.yaml
  # - storage-class.yaml

helmCharts:
- name: longhorn
  includeCRDs: true
  namespace: longhorn-system
  releaseName: longhorn
  # valuesInline:
  version: 1.5.1
  repo: https://charts.longhorn.io
  valuesInline:
    # MicroK8s kubelet root dir.
    csi:
      kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet"

patches:
  - path: ./service-account.yaml
  - path: ./longhorn-pre-upgrade.yaml