apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # The Job needs to run after the `longhorn-system` service account is created.
    # The SA is on sync-wave -2. The Helm chart set's the Job during the "PreSync"
    # phase, which runs before all resources are created, so the hook is set to
    # "Sync".
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: Sync
  name: longhorn-pre-upgrade
  namespace: longhorn-system
  