apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-driver-nfs-system
resources:
  - privileged-scc-binding.yaml
  - storageclass.yaml
  - storageclass-mass.yaml
helmCharts:
  - name: csi-driver-nfs
    version: 4.13.4
    repo: https://kubernetes-csi.github.io/csi-driver-nfs
    releaseName: csi-driver-nfs
    namespace: csi-driver-nfs-system
    valuesInline:
      controller:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        enableSnapshotter: false
      externalSnapshotter:
        enabled: false
        customResourceDefinitions:
          enabled: false
