apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-test
# resources: []

helmCharts:
- name: vcluster
  includeCRDs: true
  releaseName: vcluster-test
  namespace: vcluster-test
  version: 0.22.0
  repo: https://charts.loft.sh
  valuesFile: ./vcluster.yaml
