---
all:
  vars:
    ansible_user: root

rubrik-nodes:
  hosts:
    rubrik-a.lab.morey.tech:
    rubrik-b.lab.morey.tech:
    rubrik-c.lab.morey.tech:

rubrik-clusters:
  hosts:
    rubrik.lab.home.morey.tech:
      cluster_name: rubrik
      nodes_group: rubrik-nodes
