apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls-cert
spec:
  dnsNames:
    - '*.rubrik.lab.home.morey.tech'
    - 'rubrik.lab.home.morey.tech'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: default-tls