apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-external-system
resources:
  - ingress-nginx-metalb.yaml
  - default-tls-cert.yaml

helmCharts:
- name: ingress-nginx
  includeCRDs: true
  releaseName: ingress-nginx-external
  version: 4.9.0
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      kind: DaemonSet
      ingressClassResource:
        name: ingress-nginx-external
        # Make this the default ingress class for the cluster.
        default: true
        controllerValue: "k8s.io/ingress-nginx-external"
      # https://github.com/kubernetes/ingress-nginx/blob/86f3af8dead82f2d0905dceddeba213751e15b50/charts/ingress-nginx/templates/_params.tpl#L18-L20
      ingressClass: ingress-nginx-external
      publishService:
        # Publish the metallb Service.
        pathOverride: "ingress-nginx-external-system/ingress-nginx-external-metallb"
      service: 
        annotations:
          argocd.argoproj.io/sync-wave: 1

patches:
  - target:
      kind: DaemonSet
    patch: |-
      # Enable ssl-passthrough on the controller.
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-ssl-passthrough
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-ssl-certificate=ingress-nginx-external-system/default-tls
