---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # After the namespace and operator are created.
spec:
  no_log: false # for debugging purposes, set to true to hide sensitive info.
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
  eda:
    disabled: true
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    storage_type: file
    ## LVM storage does not support ReadWriteMany. Instead the PV is created manually below.
    file_storage_storage_class: ""
    file_storage_size: 50Gi
  lightspeed:
    disabled: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-automation-platform-hub-file-storage 
spec:
  capacity:
    storage: 50Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /storage-mass/ocp-mgmt/ansible-automation-platform/hub-file-storage
    server: "192.168.3.19"
  persistentVolumeReclaimPolicy: Retain