apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-internal-metallb
  annotations:
    metallb.universe.tf/address-pool: rubrik-static-address-pool
    loadBalancerIP: 10.8.0.1
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.8.0.1
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: mqtts
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-internal
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
