---
all:
  hosts:
    ms-01.home.morey.tech:
    ocp-lab-lb.rh-lab.morey.tech:
    pfsense.home.morey.tech:
      ansible_user: admin
  vars:
    ansible_user: root
pvems:
  hosts:
    ms-02.home.morey.tech:
    ms-03.home.morey.tech:
    ms-04.home.morey.tech:
ocp-lab:
  hosts:
    ocp-lab-02.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6102
      mac_address: bc:24:11:d1:b0:b2
      ip_address: 192.168.6.102
    ocp-lab-03.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6103
      mac_address: bc:24:11:12:e3:0c
      ip_address: 192.168.6.103
    ocp-lab-04.rh-lab.morey.tech:
      pve_node: ms-04
      pve_vm_id: 6104
      mac_address: bc:24:11:8e:e1:ff
      ip_address: 192.168.6.104
  vars:
    cluster_name: ocp-lab
    cluster_dns_zone: "rh-lab.morey.tech"
    # cluster_fqdn: "{{ cluster_name }}.{{ cluster_dns_zone }}"
    cluster_version: 4.18.5
    ssh_authorized_keys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBGTLmphmNBJtYpgYVVZrCvu3Hiwfox9szObUvwrqo4 nmorey-mac"
    high_availability_mode: "Full"
    cluster_network_cidr: "10.128.0.0/14"
    cluster_network_host_prefix: "23"
    service_networks:
      - cidr: "172.30.0.0/16"
    machine_networks:
      - cidr: "192.168.6.0/24"
    api_vips: [ip: "192.168.6.199"]
    ingress_vips: [ip: "192.168.6.198"]
    image_type: "full-iso"
