---
all:
  hosts:
    ms-01.home.morey.tech:
    pfsense.home.morey.tech:
      ansible_user: admin
    dns.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6100
      ip_address: "192.168.6.100"
      mac_address: "bc:24:11:3b:7b:8f"
  vars:
    ansible_user: root
    cluster_dns_zone: "rh-lab.morey.tech"
    machine_networks:
      - cidr: "192.168.6.0/24"
    gateway_ip: "192.168.6.1"
    net_prefix: "24"
    vlan_tag: "6"
    # high_availability_mode: "Full"  # Dnyamic based on node count.
    cluster_network_cidr: "10.128.0.0/14"
    cluster_network_host_prefix: "23"
    service_networks:
      - cidr: "172.30.0.0/16"
    image_type: "minimal-iso"
    ssh_authorized_keys: |-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIzXVreWXQDh76+WRu9ivOuy8E8dDVOs0UfQpbhV/l9iydhTdPAWvRhbqCKE409rAG3MsZGBBXUWoRwVRtiVZZSBRQw65Pnhhvp4D8Hy4C4ymuTz32nteHrzTX3N+ebMkTbKtMmyCS/KCPcHnk3f6fKcJ99x3Y6NxdXunk6/Y6rkZ9qE0yJ+g0DLNKN7I7b6hkslQ6GKtTLjwJEWQboAQUud6XKHZe0pZzaUyo66gSto+C51kQo98bAvD0AW/urtky4uYYn5vInolFR9/jvvktl8bQhCNvU95L+Tim0Kv9Q2ObSJ5VlXjmWw0XS9IBnr18E3mrgUDwrpvm1zPGlV1lLhDnNqxppmau+XWNlmm/ft4KLQLai0vxXtZLCZ7WG5LSFAFyTwdofSRXFBDp/hPASY+DAMhE5ySnmSDVJ239TAs91SalKvT8unAcdXP5XFJhCQRXAFbamkLk6BaqxzBD75sp4VqZj50IDT9C0mzzXEsUdx+FaqP+Hm0rgXNra/U= morey-tech@desktop-nick
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACkgEiCPZmF5IWfe3JST2fZeIBnMTeI1yX4v0QuauVM9+ETdT2UGBuzSpnKHLj0teOIPfXyEwEKKV5p+0zXLc2IigBlx/czMk3VStTii93TsD7bqdH35Pbh4RPpHv6v5l2W8z7TmlooeKjSNVNihu5BPM94TxUFLeVQ6etj1YVU/+/QkA== nmorey@nmorey-mac

pvems:
  hosts:
    ms-02.home.morey.tech:
    ms-03.home.morey.tech:
    ms-04.home.morey.tech:

ocp-lab-nodes:
  hosts:
    ocp-lab-01.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6101
      mac_address: bc:24:11:8e:e1:ff
      ip_address: 192.168.6.101
    # ocp-lab-02.rh-lab.morey.tech:
    #   pve_node: ms-03
    #   pve_vm_id: 6102
    #   mac_address: bc:24:11:d1:b0:b2
    #   ip_address: 192.168.6.102
    # ocp-lab-03.rh-lab.morey.tech:
    #   pve_node: ms-04
    #   pve_vm_id: 6103
    #   mac_address: bc:24:11:12:e3:0c
    #   ip_address: 192.168.6.103
  vars:
    cores: 16
    memory: 24576

ocp-dev-nodes:
  hosts:
    ocp-dev-01.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6111
      mac_address: bc:24:11:1a:2b:3c
      ip_address: 192.168.6.111
    # ocp-dev-02.rh-lab.morey.tech:
    #   pve_node: ms-02
    #   pve_vm_id: 6112
    #   mac_address: bc:24:11:4d:5e:6f
    #   ip_address: 192.168.6.112
    # ocp-dev-03.rh-lab.morey.tech:
    #   pve_node: ms-04
    #   pve_vm_id: 6113
    #   mac_address: bc:24:11:7a:8b:9c
    #   ip_address: 192.168.6.113
  vars:
    cores: 16
    memory: 24576

ocp-prd-nodes:
  hosts:
    ocp-prd-01.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6121
      mac_address: bc:24:11:2a:3b:4c
      ip_address: 192.168.6.121
    ocp-prd-02.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6122
      mac_address: bc:24:11:5d:6e:7f
      ip_address: 192.168.6.122
    ocp-prd-03.rh-lab.morey.tech:
      pve_node: ms-04
      pve_vm_id: 6123
      mac_address: bc:24:11:8a:9b:ac
      ip_address: 192.168.6.123
  vars:
    cores: 8
    memory: 16384

ocp-clusters:
  hosts:
    ocp-lab.rh-lab.morey.tech:
      cluster_name: ocp-lab
      cluster_version: 4.18.6
      nodes_group: ocp-lab-nodes
      api_vips: [ip: '192.168.6.109']
      ingress_vips: [ip: '192.168.6.108']
    ocp-dev.rh-lab.morey.tech:
      cluster_name: ocp-dev
      cluster_version: 4.18.5
      nodes_group: ocp-dev-nodes
      api_vips: [ip: '192.168.6.119']
      ingress_vips: [ip: '192.168.6.118']
    ocp-prd.rh-lab.morey.tech:
      cluster_name: ocp-prd
      cluster_version: 4.18.5
      nodes_group: ocp-prd-nodes
      api_vips: [ip: '192.168.6.129']
      ingress_vips: [ip: '192.168.6.128']
  vars:
    ansible_host: localhost
    ansible_connection: local
