---
all:
  hosts:
    ms-01.home.morey.tech:
    pfsense.home.morey.tech:
      ansible_user: admin
    dns.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6101
      ip_address: "192.168.6.101"
      net_prefix: "24"
      gateway_ip: "192.168.6.1"
      mac_address: "bc:24:11:3b:7b:8f"
      dns_zone: "rh-lab.morey.tech"
  vars:
    ansible_user: root
    ssh_authorized_keys: |-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIzXVreWXQDh76+WRu9ivOuy8E8dDVOs0UfQpbhV/l9iydhTdPAWvRhbqCKE409rAG3MsZGBBXUWoRwVRtiVZZSBRQw65Pnhhvp4D8Hy4C4ymuTz32nteHrzTX3N+ebMkTbKtMmyCS/KCPcHnk3f6fKcJ99x3Y6NxdXunk6/Y6rkZ9qE0yJ+g0DLNKN7I7b6hkslQ6GKtTLjwJEWQboAQUud6XKHZe0pZzaUyo66gSto+C51kQo98bAvD0AW/urtky4uYYn5vInolFR9/jvvktl8bQhCNvU95L+Tim0Kv9Q2ObSJ5VlXjmWw0XS9IBnr18E3mrgUDwrpvm1zPGlV1lLhDnNqxppmau+XWNlmm/ft4KLQLai0vxXtZLCZ7WG5LSFAFyTwdofSRXFBDp/hPASY+DAMhE5ySnmSDVJ239TAs91SalKvT8unAcdXP5XFJhCQRXAFbamkLk6BaqxzBD75sp4VqZj50IDT9C0mzzXEsUdx+FaqP+Hm0rgXNra/U= morey-tech@desktop-nick
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACkgEiCPZmF5IWfe3JST2fZeIBnMTeI1yX4v0QuauVM9+ETdT2UGBuzSpnKHLj0teOIPfXyEwEKKV5p+0zXLc2IigBlx/czMk3VStTii93TsD7bqdH35Pbh4RPpHv6v5l2W8z7TmlooeKjSNVNihu5BPM94TxUFLeVQ6etj1YVU/+/QkA== nmorey@nmorey-mac
pvems:
  hosts:
    ms-02.home.morey.tech:
    ms-03.home.morey.tech:
    ms-04.home.morey.tech:
ocp-lab:
  children:
    ocp-lab-nodes:
  hosts:
    # Used primarily to get group_vars in playbook.
    ocp-lab.rh-lab.morey.tech:
      ansible_host: localhost
      ansible_connection: local
      nodes_group: ocp-lab-nodes
  vars:
    cluster_name: ocp-lab
    cluster_dns_zone: "rh-lab.morey.tech"
    # cluster_fqdn: "{{ cluster_name }}.{{ cluster_dns_zone }}"
    cluster_version: 4.18.5
    high_availability_mode: "Full"
    cluster_network_cidr: "10.128.0.0/14"
    cluster_network_host_prefix: "23"
    service_networks:
      - cidr: "172.30.0.0/16"
    machine_networks:
      - cidr: "192.168.6.0/24"
    api_vips: [ip: "192.168.6.109"]
    ingress_vips: [ip: "192.168.6.108"]
    image_type: "minimal-iso"
    gateway_ip: "192.168.6.1"
    net_prefix: "24"

ocp-lab-nodes:
  hosts:
    ocp-lab-02.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6102
      mac_address: bc:24:11:d1:b0:b2
      ip_address: 192.168.6.102
    ocp-lab-03.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6103
      mac_address: bc:24:11:12:e3:0c
      ip_address: 192.168.6.103
    ocp-lab-04.rh-lab.morey.tech:
      pve_node: ms-04
      pve_vm_id: 6104
      mac_address: bc:24:11:8e:e1:ff
      ip_address: 192.168.6.104

ocp-dev:
  children:
    ocp-dev-nodes:
  hosts:
    # Used primarily to get group_vars in playbook.
    ocp-dev.rh-lab.morey.tech:
      ansible_host: localhost
      ansible_connection: local
      nodes_group: ocp-dev-nodes
  vars:
    cluster_name: ocp-dev
    cluster_dns_zone: "rh-lab.morey.tech"
    cluster_version: 4.18.5
    high_availability_mode: "Full"
    cluster_network_cidr: "10.128.0.0/14"
    cluster_network_host_prefix: "23"
    service_networks:
      - cidr: "172.30.0.0/16"
    machine_networks:
      - cidr: "192.168.6.0/24"
    api_vips: [ip: "192.168.6.119"]
    ingress_vips: [ip: "192.168.6.118"]
    image_type: "minimal-iso"
    gateway_ip: "192.168.6.1"
    net_prefix: "24"
ocp-dev-nodes:
  hosts:
    ocp-dev-02.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6112
      mac_address: bc:24:11:1a:2b:3c
      ip_address: 192.168.6.112
    ocp-dev-03.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6113
      mac_address: bc:24:11:4d:5e:6f
      ip_address: 192.168.6.113
    ocp-dev-04.rh-lab.morey.tech:
      pve_node: ms-04
      pve_vm_id: 6114
      mac_address: bc:24:11:7a:8b:9c
      ip_address: 192.168.6.114