---
all:
  hosts:
    ms-01.home.morey.tech:
    ocp-lab-lb.rh-lab.morey.tech:
  vars:
    ansible_user: root
pvems:
  hosts:
    ms-02.home.morey.tech:
    ms-03.home.morey.tech:
    ms-04.home.morey.tech:
ocp-lab:
  hosts:
    ocp-lab-02.rh-lab.morey.tech:
      pve_node: ms-02
      pve_vm_id: 6102
      mac_address: BC:24:11:46:AD:55
    ocp-lab-03.rh-lab.morey.tech:
      pve_node: ms-03
      pve_vm_id: 6103
      mac_address: BC:24:11:27:1B:51
    ocp-lab-04.rh-lab.morey.tech:
      pve_node: ms-04
      pve_vm_id: 6104
      mac_address: BC:24:11:38:2C:CC