kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: "{{ ansible_hostname }}"
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  # Exposing the api server to the internal network for early development.
  apiServerAddress: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  apiServerPort: 6443