---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
spec:
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    storage_type: file
    ## The storage class must normally support ReadWriteMany, but not on SNO.
    # file_storage_storage_class: <your-read-write-many-storage-class>
    file_storage_size: 50Gi

  lightspeed:
    disabled: true
