apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
# resources:
#   - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/baremetal/deploy.yaml
# patches:
#   - path: enable-ssl-passthrough-patch.yaml
#     target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: ingress-nginx-controller