apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # The service account needs to exist for the pre-upgrade job to run. The
    # job is set to phase -1 to run before all other resources. -2 is used to
    # on the SA to be created before the job.
    argocd.argoproj.io/sync-wave: "-2"
  name: longhorn-service-account
  namespace: longhorn-system