apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: example
  annotations:
    metallb.universe.tf/address-pool: rubrik-address-pool
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: guestbook-ui