apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager-system
# resources:
#   - cloudflare-api-token-secret.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  version: 1.14.2
  repo: https://charts.jetstack.io
  valuesInline:
    installCRDs: true
    # fix webhook ca inject annoation
    # Kustomize does not set the Release.namespace which breaks stuff (e.g. sets it to default).
    namespace: cert-manager-system
    extraArgs:
      - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
      # - '--feature-gates=ExperimentalGatewayAPISupport=true'
    global:
      leaderElection:
        # Override the namespace used for the leader election lease
        namespace: "cert-manager-system"
