apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: 8.1.3
    helm.sh/chart: valkey-3.0.22
  name: netbox-demo-valkey-primary
  namespace: netbox-demo
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: netbox-demo
      app.kubernetes.io/name: valkey
