apiVersion: 1
prune: true
datasources:
  - name: OCP Management
    uid: ocp-mgmt
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc:9091
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: GET
      prometheusType: Thanos
      timeInterval: 30s
      queryTimeout: 60s
      timeout: "60"
      manageAlerts: false
      httpHeaderName1: Authorization
      tlsAuthWithCACert: true
      tlsSkipVerify: false
      serverName: thanos-querier.openshift-monitoring.svc
    secureJsonData:
      httpHeaderValue1: Bearer $OCP_MGMT_METRICS_TOKEN
      tlsCACert: $OCP_MGMT_SERVICE_CA
