apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - serviceaccounts.yaml
  - credentials.yaml
  - ocp-mgmt-credentials.yaml
  - ocp-home-credentials.yaml
  - qnap-credentials.yaml
  - mikrotik-credentials.yaml
  - storage.yaml
  - grafana.yaml
  - prometheus.yaml
  - alloy.yaml
  - blackbox-exporter.yaml
  - services.yaml
  - route.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: alloy-config
    files:
      - config.alloy
      - qnap-snmp.yml=qnap/snmp.yml
      - mikrotik-snmp.yml=mikrotik/snmp.yml
  - name: blackbox-exporter-config
    files:
      - blackbox.yml
  - name: grafana-datasources
    files:
      - datasources.yaml
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yaml
  - name: grafana-dashboards
    files:
      - dashboards/ocp-mgmt.json
      - dashboards/ocp-home.json
      - dashboards/qnap.json
      - dashboards/mikrotik.json
      - dashboards/overview.json
