apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - serviceaccounts.yaml
  - credentials.yaml
  - ocp-mgmt-credentials.yaml
  - ocp-home-credentials.yaml
  - qnap-credentials.yaml
  - mikrotik-credentials.yaml
  - unifi-credentials.yaml
  - pfsense-credentials.yaml
  - tautulli-credentials.yaml
  - tautulli-exporter.yaml
  - sabnzbd-credentials.yaml
  - sabnzbd-exporter.yaml
  - storage.yaml
  - grafana.yaml
  - prometheus.yaml
  - alloy.yaml
  - blackbox-exporter.yaml
  - services.yaml
  - route.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: sabnzbd-exporter-config
    files:
      - config.yml=sabnzbd/config.yml
  - name: tautulli-exporter-config
    files:
      - config.yml=tautulli/config.yml
  - name: grafana-config
    files:
      - grafana.ini
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: alloy-config
    files:
      - config.alloy
      - qnap-snmp.yml=qnap/snmp.yml
      - mikrotik-snmp.yml=mikrotik/snmp.yml
      - unifi-snmp.yml=unifi/snmp.yml
      - pfsense-snmp.yml=pfsense/snmp.yml
  - name: blackbox-exporter-config
    files:
      - blackbox.yml
  - name: grafana-datasources
    files:
      - datasources.yaml
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yaml
  - name: grafana-dashboards
    files:
      - dashboards/ocp-home.json
      - dashboards/qnap.json
      - dashboards/mikrotik.json
      - dashboards/overview.json
  - name: grafana-ocp-mgmt-dashboard
    files:
      - dashboards/ocp-mgmt.json
  - name: grafana-pfsense-dashboard
    files:
      - dashboards/pfsense.json
  - name: grafana-media-dashboard
    files:
      - dashboards/media.json
  - name: grafana-unifi-dashboard
    files:
      - dashboards/unifi.json
