apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocp-home-metrics-token-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: ocp-home-metrics-token-v1
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: 762ec6ea-79b5-4e9f-be81-b4dc014da106
        property: password
