apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pfsense-snmp-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: pfsense-snmp-v1
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        snmp-auth.yml: |
          auths:
            pfsense_v3:
              version: 3
              security_level: authPriv
              auth_protocol: SHA
              priv_protocol: AES
              username: {{ .username | toJson }}
              password: {{ .password | toJson }}
              priv_password: {{ .priv_password | toJson }}
  data:
    - secretKey: username
      remoteRef:
        key: 913a8afa-4bfc-4dd5-91b0-b4dd0018d51d
        property: username
    - secretKey: password
      remoteRef:
        key: 913a8afa-4bfc-4dd5-91b0-b4dd0018d51d
        property: password
    - secretKey: priv_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 913a8afa-4bfc-4dd5-91b0-b4dd0018d51d
        property: priv_password
