apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qnap-snmp-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: qnap-snmp-v1
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        snmp-auth.yml: |
          auths:
            qnap_v3:
              version: 3
              security_level: authPriv
              auth_protocol: SHA
              priv_protocol: DES
              username: {{ .username | toJson }}
              password: {{ .password | toJson }}
              priv_password: {{ .priv_password | toJson }}
  data:
    - secretKey: username
      remoteRef:
        key: 29df3066-0d03-464d-bf35-b4dc017a372e
        property: username
    - secretKey: password
      remoteRef:
        key: 29df3066-0d03-464d-bf35-b4dc017a372e
        property: password
    - secretKey: priv_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 29df3066-0d03-464d-bf35-b4dc017a372e
        property: priv_password
