apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-api-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: sabnzbd-api-v1
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: e1126683-318a-4b75-bb41-b4de0116104f
        property: password
