apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-exporter
automountServiceAccountToken: false
