apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg-nvme
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg-nvme
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alloy
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg-nvme
  resources:
    requests:
      storage: 5Gi
