apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli-api-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: tautulli-api-v1
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: aef8aa11-b859-457f-b1e3-b4dd01844a86
        property: password
