apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-snmp-v1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: unifi-snmp-v1
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        snmp-auth.yml: |
          auths:
            unifi_v3:
              version: 3
              security_level: authPriv
              auth_protocol: SHA
              priv_protocol: AES
              username: {{ .username | toJson }}
              password: {{ .password | toJson }}
              priv_password: {{ .password | toJson }}
  data:
    - secretKey: username
      remoteRef:
        key: 9773aa8d-9fcf-4a05-9152-b4de00156fda
        property: username
    - secretKey: password
      remoteRef:
        key: 9773aa8d-9fcf-4a05-9152-b4de00156fda
        property: password
