apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  target:
    name: example-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .user }}
        password: |-
          {{ .pass }}
        testKey: |-
          {{ .testKey }}
  data:
    - secretKey: user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f88dbe25-e005-4435-b026-b121010ad06f
        property: username
    - secretKey: pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f88dbe25-e005-4435-b026-b121010ad06f
        property: password
    # Example with a custom Field in the bitwarden vault item
    - secretKey: testKey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f88dbe25-e005-4435-b026-b121010ad06f
        property: testKey