---
all:
  hosts:
    monitoring.lab.morey.tech:
      ansible_host: 192.168.3.100
      vm_id: 3100
      pve_node: ms-02
      mac_address: BC:24:11:7B:70:B7
      vlan_tag: 3
      ssh_authorized_keys: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIzXVreWXQDh76+WRu9ivOuy8E8dDVOs0UfQpbhV/l9iydhTdPAWvRhbqCKE409rAG3MsZGBBXUWoRwVRtiVZZSBRQw65Pnhhvp4D8Hy4C4ymuTz32nteHrzTX3N+ebMkTbKtMmyCS/KCPcHnk3f6fKcJ99x3Y6NxdXunk6/Y6rkZ9qE0yJ+g0DLNKN7I7b6hkslQ6GKtTLjwJEWQboAQUud6XKHZe0pZzaUyo66gSto+C51kQo98bAvD0AW/urtky4uYYn5vInolFR9/jvvktl8bQhCNvU95L+Tim0Kv9Q2ObSJ5VlXjmWw0XS9IBnr18E3mrgUDwrpvm1zPGlV1lLhDnNqxppmau+XWNlmm/ft4KLQLai0vxXtZLCZ7WG5LSFAFyTwdofSRXFBDp/hPASY+DAMhE5ySnmSDVJ239TAs91SalKvT8unAcdXP5XFJhCQRXAFbamkLk6BaqxzBD75sp4VqZj50IDT9C0mzzXEsUdx+FaqP+Hm0rgXNra/U= morey-tech@desktop-nick
        ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACkgEiCPZmF5IWfe3JST2fZeIBnMTeI1yX4v0QuauVM9+ETdT2UGBuzSpnKHLj0teOIPfXyEwEKKV5p+0zXLc2IigBlx/czMk3VStTii93TsD7bqdH35Pbh4RPpHv6v5l2W8z7TmlooeKjSNVNihu5BPM94TxUFLeVQ6etj1YVU/+/QkA== nmorey@nmorey-mac
      cores: 4
      memory: 8192
  vars:
    ansible_user: root
