apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-devspaces
resources:
  - checluster.yaml
  - github-oauth.yaml
  - claude-code-api-key.yaml
  - getting-started-samples.yaml
  - vscode-editor-configurations.yaml
  - ocp-home-kubeconfig.yaml
