# Global VS Code extensions, replicated to Dev Spaces user namespaces.
# https://docs.redhat.com/en/documentation/red_hat_openshift_dev_spaces/3.25/html/administration_guide/configuring-visual-studio-code
apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
data:
  extensions.json: |
    {
      "recommendations": [
        "openai.chatgpt"
      ]
    }
