---
- name: Configure Rubrik nodes
  hosts:
    - rubrik-nodes
  become: true

  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - nfs-common
          - open-iscsi
          - snapd
          - parted
        state: present
        update_cache: true

    - name: Install tools (with snap)
      community.general.snap:
        name:
          - jq
          - kubectl

    # sudo snap install microk8s --classic
    # Separate because it requires `--classic`.
    - name: Install microk8s (with snap)
      community.general.snap:
        name:
          - microk8s
        classic: true  # required for microk8s with full system access.

    # sudo usermod -a -G microk8s {{ ansible_user }}
    - name: Apending microk8s group to user {{ ansible_user }}
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: microk8s  # Add the user to a group
        append: true        # Add the user to the group without removing from other groups

    # sudo chown -f -R {{ ansible_user }} ~/.kube
    - name: Set ownership of ~/.kube for {{ ansible_user }}
      ansible.builtin.file:
        path: ~/.kube
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: true  # Equivalent to -R
        force: true    # Equivalent to -f
        state: directory  # Ensure it's treated as a directory

    - name: Output the microk8s kubeconfig
      ansible.builtin.command: "/snap/bin/microk8s config"
      register: kubeconfig
      changed_when: false

    # - name: Enable microk8s ingress
    #   ansible.builtin.command: "microk8s enable ingress"
    #   changed_when: false

    # - name: Display kubeconfig
    #   ansible.builtin.debug:
    #     var: kubeconfig.stdout_lines

    - name: Create .kube directory
      ansible.builtin.file:
        path: "/home/ubuntu/.kube"
        state: directory
        mode: '0750'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Save kubeconfig to environment folder
      run_once: true
      ansible.builtin.copy:
        content: "{{ kubeconfig.stdout }}"
        dest: "/home/ubuntu/.kube/config"
        mode: '0640'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Fetch kubeconfig
      run_once: true
      ansible.builtin.fetch:
        src: "/home/ubuntu/.kube/config"
        dest: "../../kubernetes/rubrik/kubeconfig.yml"
        flat: true
        mode: '0640'
        owner: "{{ ansible_env.USER }}"

    - name: Create partition on the disk
      community.general.parted:
        device: /dev/vda
        state: present
        number: 1
        part_start: 0%
        part_end: 100%

    - name: Format the partition
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vda1

    - name: Create /var/lib/longhorn/ directory
      ansible.builtin.file:
        path: /var/lib/longhorn/
        state: directory
        mode: '0640'

    - name: Mount the partition to /var/lib/longhorn/
      ansible.posix.mount:
        path: /var/lib/longhorn/
        src: /dev/vda1
        fstype: ext4
        state: mounted
