kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: aap-external
spec:
  host: aap.ocp-gpu.morey.tech
  path: /
  to:
    kind: Service
    name: aap
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: aap-ocp-gpu-morey-tech
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
spec:
  endpoints:
  - dnsName: aap.ocp-gpu.morey.tech
    recordTTL: 300
    recordType: CNAME
    targets:
    - home.morey.tech