---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap-operator
  namespace: aap-operator-system
spec:
  targetNamespaces:
    - aap-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aap-operator
  namespace: aap-operator-system
spec:
  channel: 'stable-2.5'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace