---
- name: Set Up Cloud-Init VM Template
  hosts: 
  - phobos.lab.home.morey.tech
  become: true

  vars:
    image_path: '/tmp/debian-10-generic-amd64.qcow2'
    vm_id: '3106'
  
  tasks:
    - name: Install required system packages
      apt: 
        name:
        - libguestfs-tools
        state: present
        update_cache: yes

    - name: Download cloud-init image.
      shell: 'wget -O {{ image_path}} https://cdimage.debian.org/cdimage/cloud/buster/20220328-962/debian-10-generic-amd64-20220328-962.qcow2'
      args:
        creates: '{{ image_path }}'

    - name: Check if root is allowed to SSH.
      shell: virt-cat --format=qcow2 -a {{ image_path}} /etc/cloud/cloud.cfg | grep disable_root
      register: check_disable_root
      changed_when: false

    - name: Allow root to SSH.
      shell: virt-edit -a {{ image_path}} /etc/cloud/cloud.cfg -e 's/disable_root:\ true/disable_root:\ false/'
      when: "check_disable_root.stdout.find('disable_root: true') != -1"

    - name: Check if root is allowed to SSH with key.
      shell: 'virt-cat --format=qcow2 -a {{ image_path}} /etc/ssh/sshd_config | grep "#PermitRootLogin prohibit-password"'
      register: check_permit_root_login
      changed_when: false

    - name: Allow root to use SSH key.
      shell: virt-edit -a {{ image_path}} /etc/ssh/sshd_config -e 's/#PermitRootLogin\ prohibit-password/PermitRootLogin\ prohibit-password/'
      when: check_disable_root.stdout