---
- name: Docker
  hosts: 
  - sandbox_nodes
  become: true

  vars:
  
  tasks:
    - name: Install required system packages
      apt: 
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - parted
        state: present
        update_cache: yes

    - name: Create a ext4 filesystem on /dev/sdb
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb
    
    - name: Mount disk to /var/lib/docker
      ansible.posix.mount:
        path: /var/lib/docker
        src: /dev/sdb
        fstype: ext4
        state: mounted

    - name: Add Docker GPG apt Key
      shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'
      args:
        creates: '/usr/share/keyrings/docker-archive-keyring.gpg'

    - name: Add Docker Repository
      shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker.list'
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
