apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: housekeeping
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.3.4
    helm.sh/chart: netbox-6.0.59
  name: netbox-demo-housekeeping
  namespace: netbox-demo
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/instance: netbox-demo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: netbox
        app.kubernetes.io/version: v4.3.4
        helm.sh/chart: netbox-6.0.59
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: housekeeping
            app.kubernetes.io/instance: netbox-demo
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: netbox
            app.kubernetes.io/version: v4.3.4
            helm.sh/chart: netbox-6.0.59
        spec:
          automountServiceAccountToken: false
          containers:
          - command:
            - /opt/netbox/venv/bin/python
            - /opt/netbox/netbox/manage.py
            - housekeeping
            image: ghcr.io/netbox-community/netbox:v4.3.4
            imagePullPolicy: IfNotPresent
            name: netbox-housekeeping
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              seLinuxOptions: {}
              seccompProfile:
                type: RuntimeDefault
            volumeMounts:
            - mountPath: /etc/netbox/config/configuration.py
              name: config
              readOnly: true
              subPath: configuration.py
            - mountPath: /run/config/netbox
              name: config
              readOnly: true
            - mountPath: /run/secrets/netbox
              name: secrets
              readOnly: true
            - mountPath: /tmp
              name: netbox-tmp
            - mountPath: /opt/netbox/netbox/media
              name: media
              readOnly: false
              subPath: ''
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: Always
            supplementalGroups: []
            sysctls: []
          serviceAccountName: netbox-demo
          volumes:
          - configMap:
              name: netbox-demo
            name: config
          - name: secrets
            projected:
              sources:
              - secret:
                  items:
                  - key: secret_key
                    path: secret_key
                  name: netbox-demo-config
              - secret:
                  items:
                  - key: email_password
                    path: email_password
                  name: netbox-demo-config
              - secret:
                  items:
                  - key: password
                    path: db_password
                  name: netbox-demo-postgresql
              - secret:
                  items:
                  - key: valkey-password
                    path: tasks_password
                  name: netbox-demo-valkey
              - secret:
                  items:
                  - key: valkey-password
                    path: cache_password
                  name: netbox-demo-valkey
          - emptyDir:
              medium: Memory
            name: netbox-tmp
          - name: media
            persistentVolumeClaim:
              claimName: netbox-demo-media
              readOnly: false
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 5
  suspend: false
