apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: 30-min-snapshot-50-retain
  namespace: longhorn-system
spec:
  concurrency: 2
  cron: '*/30 * * * *'  # Every 15 minutes.
  # Having default in groups will automatically schedule this recurring job to any volume with no recurring job.
  groups:
  - default
  name: 30-min-snapshot-50-retain
  retain: 50  # Just over a day of retained.
  task: snapshot
