resources:
  - namespace.yaml
  - ingress.yaml
  - default-daily-backup.yaml
  - default-daily-snapshot.yaml
  # - storage-class.yaml

helmCharts:
- name: longhorn
  includeCRDs: true
  namespace: longhorn-system
  releaseName: longhorn
  # valuesInline:
  version: 1.5.1
  repo: https://charts.longhorn.io
  valuesInline:
    # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
    # MicroK8s kubelet root dir.
    csi:
      kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet"
    defaultSettings: 
      # Endpoint used to access the backupstore.
      backupTarget: nfs://192.168.1.20:/storage-mass/rubrik/longhorn
      # Allow multiple replicas on a single node. Rebalance replicas across nodes.
      # https://github.com/morey-tech/homelab/issues/39
      replicaSoftAntiAffinity: true
      replicaAutoBalance: best-effort

patches:
  - path: ./service-account.yaml
  - path: ./longhorn-pre-upgrade.yaml