apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-appset
spec:
  goTemplate: true
  syncPolicy:
    applicationsSync: create-update
  generators:
  - git:
      repoURL: https://github.com/morey-tech/homelab.git
      revision: HEAD
      directories:
      - path: kubernetes/ocp-mgmt/system/external-secrets
      - path: kubernetes/ocp-mgmt/system/htpass-admin
      - path: kubernetes/ocp-mgmt/system/cert-manager-operator
      - path: kubernetes/ocp-mgmt/system/cert-manager
      - path: kubernetes/ocp-mgmt/system/openshift-ingress
      - path: kubernetes/ocp-mgmt/system/openshift-apiserver
      - path: kubernetes/ocp-mgmt/system/openshift-monitoring
      - path: kubernetes/ocp-mgmt/system/csi-driver-nfs
      - path: kubernetes/ocp-mgmt/system/openshift-operators
      - path: kubernetes/ocp-mgmt/system/openshift-devspaces
  ignoreApplicationDifferences:
    - jsonPointers:
      # Allow automated sync policy to be disabled manually.
      - /spec/syncPolicy/automated
      # Allow target revision to be set manually for PR testing,
      - /spec/source/targetRevision
  template:
    metadata:
      name: '{{.path.basename}}-system'
    spec:
      project: default
      source:
        repoURL: https://github.com/morey-tech/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}-system'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - allowEmpty=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            openshift.io/cluster-monitoring: "true"
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
  templatePatch: |
    {{- if eq .path.basename "external-secrets" }}
    spec:
      syncPolicy:
        syncOptions:
        - allowEmpty=true
        - CreateNamespace=true
        - ServerSideApply=true
    {{ end }}
    {{- if or (eq .path.basename "cert-manager") (eq .path.basename "cert-manager-operator") }}
    spec:
      destination:
        namespace: {{.path.basename}}
      syncPolicy:
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - SkipDryRunOnMissingResource=true
    {{ end }}
    {{- if or (eq .path.basename "openshift-ingress") (eq .path.basename "openshift-apiserver") }}
    spec:
      destination:
        namespace: {{ if eq .path.basename "openshift-ingress" }}openshift-ingress{{ else }}openshift-config{{ end }}
      syncPolicy:
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true
    {{ end }}
    {{- if eq .path.basename "openshift-monitoring" }}
    spec:
      destination:
        namespace: openshift-monitoring
      syncPolicy:
        syncOptions: []
    {{ end }}
    {{- if or (eq .path.basename "openshift-operators") (eq .path.basename "openshift-devspaces") }}
    spec:
      destination:
        namespace: {{.path.basename}}
      syncPolicy:
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - SkipDryRunOnMissingResource=true
    {{ end }}
