apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rubrik-static-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.8.0.0/16
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rubrik-dynamic-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.9.0.0/16
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-unifi-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.13/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
spec:
  ipAddressPools:
  - rubrik-static-address-pool
  - rubrik-dynamic-address-pool
  - lan-unifi-address-pool
  # Advertise each route as a /32 (i.e. single IP address).
  aggregationLength: 32
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: pfsense-peer
spec:
  myASN: 64501
  # ASN of pfSense.
  peerASN: 64500
  peerAddress: 192.168.3.1