apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=confirm
spec:
  components:
    dashboard:
      managementState: Managed
    kserve:
      managementState: Managed
      nim:
        managementState: Removed
      modelsAsService:
        managementState: Removed
      wva:
        managementState: Removed
    aigateway:
      managementState: Removed
      batchGateway:
        managementState: Removed
    aipipelines:
      managementState: Removed
    feastoperator:
      managementState: Removed
    kueue:
      managementState: Removed
    llamastackoperator:
      managementState: Removed
    mcplifecycleoperator:
      managementState: Removed
    mlflowoperator:
      managementState: Removed
    modelregistry:
      managementState: Removed
    ogx:
      managementState: Removed
    ray:
      managementState: Removed
    sparkoperator:
      managementState: Removed
    trainer:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    trustyai:
      managementState: Removed
    workbenches:
      managementState: Removed
