apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-appset
spec:
  generators:
  - git:
      repoURL: https://github.com/morey-tech/homelab.git
      revision: HEAD
      directories:
      - path: kubernetes/rubrik/system/*
  ignoreApplicationDifferences:
    - jsonPointers:
      # Allow automated sync policy to be disabled manually.
      - /spec/syncPolicy/automated
      # Allow target revision to be set manually for PR testing,
      - /spec/source/targetRevision
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/morey-tech/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-system'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - allowEmpty=true
        - CreateNamespace=true
  templatePatch: |
    {{- if path.basename == "metallb" }}
    spec:
      ignoreDifferences:
        # Ignore generated caBundle on MetalLB 
        - kind: CustomResourceDefinition
          group: apiextensions.k8s.io
          jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
    {{- end }}
    {{- if path.basename == "k8s-gateway" }}
    spec:
      ignoreDifferences:
        - kind: Deployment
          group: apps
          jsonPointers:
          - /spec/template/metadata/annotations/checksum~1config
    {{- end }}
