apiVersion: v1
data:
  valkey-password: bXBXcUhiSlJ2bw==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: netbox-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/version: 8.1.3
    helm.sh/chart: valkey-3.0.22
  name: netbox-demo-valkey
  namespace: netbox-demo
type: Opaque
