apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - library-pvc.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: immich-server
  path: deployment-patch.yaml

helmCharts:
- name: immich
  includeCRDs: true
  version: 0.8.4
  repo: https://immich-app.github.io/immich-charts
  releaseName: immich
  namespace: immich
  valuesInline:
    image:
      tag: v1.121.0
      pullPolicy: IfNotPresent

    immich:
      persistence:
        library:
          existingClaim: changeme  # see deployment-patch.yaml

    postgresql:
      enabled: true
      image:
        repository: tensorchord/pgvecto-rs
        tag: pg14-v0.2.0
      primary:
        # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl
        resourcesPreset: small

    redis:
      enabled: true

    server:
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: ingress-nginx-internal
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: 2048m
          hosts:
            - host: immich.rubrik.lab.home.morey.tech
              paths:
              - path: /
                pathType: Prefix
          tls:
          - secretName: immich.rubrik.lab.home.morey.tech
            hosts:
            - immich.rubrik.lab.home.morey.tech